---
stages:
- name: BUILD - Fastlane (APK)
  inputs:
  - type: git
    branch: master
    service: ${APP_REPO}
  triggers:
  - type: stage
  properties:
  - name: gitPushUser
    value: vinapp
    type: text
  - name: gitPushToken
    value: 6aba5bac3e0e7fecc9cb6ca4ff623325191117c6
    type: text
  - name: gitPushEmail
    value: vin.app@gmail.com
    type: text
  - name: appRepo
    value: appRepo Name
    type: text
  - name: apkGitPushUrl
    value: https://$gitPushToken:x-oauth-basic@github.com/vinapp/$appRepo master
    type: text  
  - name: push
    value: true
    type: text
  - name: analytics
    value: false
    type: text
  jobs:
  - name: Install Android SDK, Fastlane and build apk
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      export JAVA_HOME=/opt/IBM/java8
      cd /home/pipeline

      if [ "$push" = "true" ]
      then
          echo "push enabled"
          # rm -rf /home/pipeline/$BUILD_ID/app
          cp -R /home/pipeline/$BUILD_ID/ReplaceFiles/push/app /home/pipeline/$BUILD_ID
      elif [ "$analytics" = "true" ]
      then
          # rm -rf /home/pipeline/$BUILD_ID/app
          echo "analytics enabled"
          cp -R /home/pipeline/$BUILD_ID/ReplaceFiles/analytics/app /home/pipeline/$BUILD_ID
      fi

      # Android sdk
      wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
      sudo apt-get install unzip
      unzip /home/pipeline/sdk-tools-linux-3859397.zip
      echo 'y' | /home/pipeline/tools/bin/sdkmanager --licenses
      echo 'y' | /home/pipeline/tools/bin/sdkmanager "platform-tools" "platforms;android-26"

      # Prereq for installing Fastlane: Install RVM
      gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      \curl -L https://get.rvm.io | bash -s stable --ruby
      source /home/pipeline/.rvm/scripts/rvm get stable --autolibs=enable
      gem -v

      # Install Fastlane
      gem install fastlane -NV

      # Build the apk file
      cd /home/pipeline/$BUILD_ID
      fastlane beta

      ls ./app/build/outputs/apk/

      cp ./app/build/outputs/apk/app-release.apk .

      # Push the generated apk for git hub for testing
      git config --global user.name $gitPushUser
      git config --global user.email $gitPushEmail
      git add app-release.apk
      git commit -m "released a new version of apk - build : ($BUILD_ID)"
      echo $apkGitPushUrl
      git push $apkGitPushUrl
- name: TEST - AppiumTestDroid
  inputs:
  - type: git
    branch: master
    service: ${SCRIPT_REPO}
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: skipDatafile
    value: 'true'
    type: text
  - name: applicationPath
    value: /home/pipeline/$BUILD_ID/appium/sample-scripts/java/app-release.apk
    type: text
  - name: executionType
    value: clientside
    type: text
  - name: test
    value: PushAnalyticsTest
    type: text
  - name: bitbarApiKey
    value: 3IMUlaWW1BW2uzESHldjo5cEU4swMqf7
    type: text
  - name: appRepo
    value: appRepo Name
    type: text
  jobs:
  - name: Test the app using Appium scripts on Bitbar
    type: builder
    fail_stage: false
    build_type: maven
    script: |-
      #!/bin/bash
      cd /home/pipeline/$BUILD_ID/appium/sample-scripts/java
      echo "Download apk file"
      wget https://github.com/vinapp/$appRepo/blob/master/app-release.apk?raw=true
      mv app-release.apk?raw=true app-release.apk
      mvn clean install -X -Dtest=$test -DexecutionType=$executionType -DapiKey=$bitbarApiKey -DapplicationPath=$applicationPath
- name: UPLOAD - Logs
  triggers:
  - type: stage
  properties:
  - name: gitToken
    value: 6aba5bac3e0e7fecc9cb6ca4ff623325191117c6
    type: text
  - name: bitbarApiKey
    value: '3IMUlaWW1BW2uzESHldjo5cEU4swMqf7:'
    type: text
  - name: bitbarAppiumClientSideProject
    value: https://cloud.testdroid.com/api/me/projects/137948056/runs
    type: text
  - name: bitbarTestReportLocation
    value: https://cloud.testdroid.com/#service/testrun/137948056/
    type: text
  - name: issueGitRepo
    value: https://api.github.com/repos/vinapp/testdroid-samples/issues
    type: text
  jobs:
  - name: LogsUpload
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      testID=$(curl -H "Accept: application/json" -u $bitbarApiKey -X GET $bitbarAppiumClientSideProject | awk -F'[:]' '{print $3}' | awk -F'[,]' '{print $1}')
      title="Test Results for build "$testID
      body="Check the detail reports here : "$bitbarTestReportLocation$testID
      curl -H "Content-Type: application/json" -H "Authorization: Bearer $gitToken" --include --request POST --data "{\"title\": \"$title\", \"body\": \"$body\"}" $issueGitRepo
