version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: icon.svg
  required:
    - build
    - app-repo
    - testscript-repo
  info:
    git url: >-
      [https://github.com/vinapp/simple-toolchain](https://github.com/vinapp/simple-toolchain)
    git branch: >-
      [master](https://github.com/vinapp/simple-toolchain/tree/master)
toolchain:
  name: 'simple-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  app-repo:
    service_id: githubpublic
    parameters:
      repo_name: 'app-repo-{{timestamp}}'
      repo_url: 'https://github.com/vinapp/sample-android-app'
      type: clone
      has_issues: false
      enable_traceability: true
  testscript-repo:
    service_id: githubpublic
    parameters:
      repo_name: 'testscript-repo-{{timestamp}}'
      type: clone
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - app-repo
        - testscript-repo
      name: '{{services.app-repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          APP_REPO: app-repo
          SCRIPT_REPO: testscript-repo
          PROD_SPACE_NAME: '{{form.pipeline.parameters.prod-space}}'
          PROD_ORG_NAME: '{{form.pipeline.parameters.prod-organization}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
        execute: false
form:
  pipeline:
    parameters:
      prod-app-name: '{{services.app-repo.parameters.repo_name}}'
    schema:
      $ref: deploy.json
